# Generated by Django 3.1.1 on 2020-10-17 04:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiposCilindros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiposcilindros',
            name='vidaUtil',
            field=models.DecimalField(decimal_places=3, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Vida útil en años'),
        ),
    ]
