# Generated by Django 3.1.1 on 2020-10-17 11:58

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('tipo_documento', models.CharField(choices=[('CC', 'CC'), ('TI', 'TI'), ('CE', 'CE')], max_length=2, verbose_name='Tipo de documento')),
                ('numero_documento', models.CharField(max_length=20, unique=True, verbose_name='Número de documento')),
                ('telefono', models.CharField(max_length=20, verbose_name='Número telefónico')),
                ('segundo_nombre', models.CharField(blank=True, max_length=100, verbose_name='Segundo nombre')),
                ('segundo_apellido', models.CharField(blank=True, max_length=100, verbose_name='Segundo apellido')),
                ('rol', models.ForeignKey(limit_choices_to={'estado': 'Activo'}, on_delete=django.db.models.deletion.CASCADE, to='Usuarios.roles', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
